### ISSUE TITLE
File access issues on macOS

### ISSUE THREAD

**Issue by AtomCrafty** [Gargaj/Bonzomatic#142]
Hey there,

I'm currently trying to set up Bonzomatic on a mac book running macOS Catalina 10.15.6, but it seems that the program is unable to access any of the additional included files. The font and config are not loaded and compiling the shader outputs a warning stating that it could not be saved. I also asked a friend running High Sierra 10.15.5 to test it and he has the same issues.

The problem does not occur when the executable (`Bonzomatic.app/Contents/MacOS/Bonzomatic`) is started directly instead of the app container. As a Windows user I'm not really familiar with the macOS app architecture, but to me this appears to be an issue with the deployed app container.

**Comment by Gargaj** [comment]
@alkama

**Comment by alkama** [comment]
Bonzomatic.app should not be put into `/Application` like other apps, since it's trying to find and access a `texture` folder, the `config.json` file and to write a `shader.glsl` file upon every compilation.
I'm running Catalina and have no other problem.
In case you need it, you could add the Bonzomatic.app to the System Preferences > Security and Privacy > Privacy > Full Disk Access list. But on my side I havent had to do it.

**Comment by AtomCrafty** [comment]
The app is located in a folder on my desktop, not in `/Application`. I  already tried adding it to the 'Full Disk Access' list, but that didn't seem to have any effect.

<img width="1680" alt="Bildschirmfoto 2020-08-05 um 17 28 56" src="https://user-images.githubusercontent.com/4553050/89432443-6c6ab500-d741-11ea-9cee-60489536a63b.png">

For now I created a simple script that starts the contained executable, but that's not an ideal solution.
```
#!/bin/bash
/Users/mario/Desktop/Bonzomatic/Bonzomatic.app/Contents/MacOS/Bonzomatic
```

**Comment by alkama** [comment]
Then my bet is on a strange permission on your Desktop folder, and possibly on the Bonzomatic folder.
Just in case I compiled a version on Catalina with XCode11.6.
I placed it there: https://alkama.com/drop/Bonzomatic_MacOS_GLFW33.zip

**Comment by AtomCrafty** [comment]
Tried placing your version in my home directory (`/Users/mario/Bonzomatic/Bonzomatic.app`), but the issue persists.

**Comment by dreness** [comment]
This is most likely due to the 'quarantine' extended attribute, which is part of a security feature called [Gatekeeper](https://eclecticlight.co/2019/10/04/will-gatekeeper-let-me-run-that-app-in-catalina/). You can check for the quarantine bit with a couple of special `ls` flags: `e` and `@`, as shown here:

```
❯ ls -ale@
total 176
drwxr-xr-x@  10 andre  staff    320 Oct 14 17:01 .
	com.apple.quarantine	   57 
drwxrwxr-x+ 264 root   admin   8448 Oct 14 16:45 ..
 0: group:everyone deny delete
-rw-r--r--@   1 andre  staff   6148 Oct 14 16:54 .DS_Store
	com.apple.FinderInfo	   32 
drwxr-xr-x@   3 andre  staff     96 Oct 14 16:45 Bonzomatic.app
	com.apple.quarantine	   57 
-rw-rw-r--@   1 andre  staff   1392 May  8  2016 LICENSE
	com.apple.quarantine	   57 
-rw-rw-r--@   1 andre  staff  56376 Jan  4  2004 ProFontWindows.ttf
	com.apple.quarantine	   57 
-rw-rw-r--@   1 andre  staff   9054 May  9 16:07 README.md
	com.apple.lastuseddate#PS	   16 
	com.apple.quarantine	   57 
-rw-rw-r--@   1 andre  staff    516 Oct 14 17:01 config.json
	com.apple.quarantine	   57 
-rw-rw-r--@   1 andre  staff     94 Mar  3  2019 file_id.diz
	com.apple.quarantine	   57 
drwxrwxr-x@   9 andre  staff    288 Oct 14 16:45 textures
	com.apple.quarantine	   57 
```

... and you can recursively nuke this extended attribute with:
`xattr -r -d com.apple.quarantine /path/to/Bonzomatic_directory`

... for example, while my current directory is the Bonzomatic directory:

```
❯ xattr -r -d 'com.apple.quarantine' .
❯ ls -ale@                            
total 176
drwxr-xr-x   10 andre  staff    320 Oct 14 17:01 .
drwxrwxr-x+ 264 root   admin   8448 Oct 14 16:45 ..
 0: group:everyone deny delete
-rw-r--r--@   1 andre  staff   6148 Oct 14 16:54 .DS_Store
	com.apple.FinderInfo	   32 
drwxr-xr-x    3 andre  staff     96 Oct 14 16:45 Bonzomatic.app
-rw-rw-r--    1 andre  staff   1392 May  8  2016 LICENSE
-rw-rw-r--    1 andre  staff  56376 Jan  4  2004 ProFontWindows.ttf
-rw-rw-r--@   1 andre  staff   9054 May  9 16:07 README.md
	com.apple.lastuseddate#PS	   16 
-rw-rw-r--    1 andre  staff    516 Oct 14 17:01 config.json
-rw-rw-r--    1 andre  staff     94 Mar  3  2019 file_id.diz
drwxrwxr-x    9 andre  staff    288 Oct 14 16:45 textures
```

After doing the above, I can confirm that Bonzomatic is now able to see the nearby textures.

Also, be aware that generally speaking macOS does prefer that Applications live in the Applications folder (although a sub-directory is fine as well). There's this other thing called [App Translocation](https://craftware.xyz/tips/App-translocation.html) that applies specifically to quarantine'd executables launched from their download location.

**Comment by AtomCrafty** [comment]
Awesome, that worked! :)
Thanks for the help @dreness.
