### ISSUE TITLE
Build failure on macOS 10.13

### ISSUE THREAD

**Issue by rnkn** [Gargaj/Bonzomatic#154]
I'm getting a build failure on macOS, but different to #145

Mac OS X version: `10.13.6`

Bonzomatic version: `615f06df9590610537250685000b2447b6393c11 - Fri Mar 19 00:00:48 2021 +0000`

The build output: [build.log](https://github.com/Gargaj/Bonzomatic/files/6308474/build.log)

**Comment by Gargaj** [comment]
@alkama

**Comment by alkama** [comment]
Ah those authorization APIs only exist since 10.4 as shown here [https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624613-authorizationstatusformediatype](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624613-authorizationstatusformediatype)

Meanwhile you can safely comment everything about requesting microphone access on your 10.13:
https://github.com/Gargaj/Bonzomatic/blob/master/src/platform_osx/Misc.mm#L20-L54

**Comment by rnkn** [comment]
Thanks, that fixed it! (I had to merge #152 to launch the app.)
