### ISSUE TITLE
Low res text and ignored config.json on macOS Ventura 13.4

### ISSUE THREAD

**Issue by danielradosa** [Gargaj/Bonzomatic#175]
I downloaded the latest release on my M2 air, and when running Bonzomatic, it doesn't use the config.json because I always see resolution prompt, even tho' I specified skipping it in json.
Then the resolution of text is very low, plus bottom menu is barely visible because of it. F11 to hide text editor doesn't work either, it just hides all my windows opened on mac. That might be a macos keyboard settings mapping issue. Just wanted to mention it as well. F5 to recompile works.
<img width="1389" alt="Snímka obrazovky 2023-06-08 o 12 01 28" src="https://github.com/Gargaj/Bonzomatic/assets/13753754/20df91de-2dda-4e1b-996d-93d195acda23">

**Comment by danielradosa** [comment]
In my macos settings i turned of the default hide all windows keyboard shortcut for F11 so its working now. however, i still havent figured out why the text is so low-res and why my config.json is not recognized.

**Comment by danielradosa** [comment]
In my macos settings i turned of the default hide all windows keyboard shortcut for F11 so its working now. however, i still havent figured out why the text is so low-res and why my config.json is not recognized.

**Comment by dreness** [comment]
Good news / bad news:

Good news: if you set `NSHighResolutionCapable` to true in the app's Info.plist, retina support is activated, which you can see in this screenshot:

<img width="589" alt="image" src="https://github.com/Gargaj/Bonzomatic/assets/5242016/3db623f8-9a97-4941-9e3f-39e8726c770b">

You can use your favorite text editor to make that change, or use this Terminal command - set the correct path to your Bonzomatic app bundle:

```
/usr/libexec/PlistBuddy -c "Set :NSHighResolutionCapable true" /path/to/Bonzomatic.app/Contents/Info.plist
```

Bad news: after making this change, mouse interactions in the code editor behave as though you aren't using a retina [backingScaleFactor](https://developer.apple.com/documentation/appkit/nswindow/1419459-backingscalefactor), so for example you can't click to move the cursor anywhere in the bottom half of the window... My GL skills are rudimentary at best, and I can't quite spot the error in the Bonzomatic code - but it's acting like the mouse interactions are calculated based on screen coordinates instead of pixel coordinates.

**Comment by danielradosa** [comment]
Amazing thanks @dreness.
