### ISSUE TITLE
Licence is misleading

### ISSUE THREAD

**Issue by marcoose777** [Gargaj/Bonzomatic#43]
The stated licence doesn't seem correct, a quick look at http://www.un4seen.com/bass.html#license should clarify this for you. It is clearly not a do as you like licence. The audio stream librarary libbass is FREEWARE, and requries payment for use outside of home/presonal use.
Are the authors aware that you've been using their software at a for profit event?
If you were continuing to develop this, then may I suggest looking at fftw (only intels math libs beat this) for fourier analysis, and RtAudio(windows, mac, and linux C++ audio) for streaming. That way you won't need to state FREEWARE home/personal use only on the licencing.

**Comment by Gargaj** [comment]
1. Bonzomatic as a software remains free to use regardless of where it's being used. The authors of Bonzomatic earn no profit off the development and use of Bonzomatic, have never did, and will continue not to.
2. There is no formal affiliation between the developers of Bonzomatic and organizers of any event. While Revision did serve as an inspiration for creating the software, the software is not exclusive to Revision and it wasn't created due to a specific request by the organizers, and as such no payments have been requested or exchanged either.
3. Revision (as an example) is not a for-profit event: it is organized by a legally registered non-profit association: http://www.tastatur-und-maus.net/en/the_association - the same is true for e.g. Solskogen where it's also been used.

As such, I strongly believe that Bonzomatic is non-commercial software, and qualifies for BASS' non-commercial license.

**Comment by marcoose777** [comment]
I wasn't trolling just pointing out a potential legal minefield should the owners of libbass take notice, and form the opinion that their rights have been violated. In such a situation the owners would probably be looking for recompense, and any users who may have flouted the freeware nature of the audio-pipeline would point to the licence terms you have indicated. Just a suggestion, but it may be worth hilighting the licence terms of libbass, if for nothing else other than to protect yourselves from litigation. 

Otherwise it's a nice little tool, I've had to hard code a font path before it would work on linux, and then create a little folder with a few textures. I did try the jsonxx approach to font path configuration, but that requries a bit more work.

Otherwise nice one, thanks

**Comment by plouet** [comment]
@marcoose777 I've implemented the equivalent function using FFTW and SDL in my [OpenBSD port/fork](https://github.com/plouet/openbsd-Bonzomatic/tree/master/src/platform_openbsd), because BASS is not available on OpenBSD.

This can be used by anyone who wants to port Bonzomatic to other platforms where BASS is not available.

**Comment by Gargaj** [comment]
This has been fixed with https://github.com/Gargaj/Bonzomatic/commit/cde5a068ba5c3cd288a15506c4693bfb9ed3e71d
